import React,{useEffect,useRef,useState} from 'react';
import {ArrowUpRight,Copy,Check,Menu,X} from 'lucide-react';
import {createRoot} from 'react-dom/client';
import './styles.css';
const PLAY_STORE_URL='https://play.google.com/store/apps/details?id=mk.triglavzivot.app&hl=en_US&pli=1';
const TOKEN_ADDRESS='';
const X_URL='https://x.com/Triglavcard';
const BUY_URL='';
const HERO_ASSETS=['n4nfp46kp.png','5oedq79cd.png','eak19hxes.png','dvc4f6g5m.png','lb6onlop6.png'];
const EXPERIENCE_ASSETS=['rsmr4stjz.png','k97coru19.png','q2v8m6x4c.png'];

function App(){
 const [menu,setMenu]=useState(false);
 const heroRail=useRef(null), experienceRail=useRef(null);
 const [copied,setCopied]=useState(false);
 const copyCA=async()=>{let ok=false;try{if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(TOKEN_ADDRESS);ok=true}}catch{}if(!ok){try{const ta=document.createElement('textarea');ta.value=TOKEN_ADDRESS;ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.focus();ta.select();ok=document.execCommand('copy');ta.remove()}catch{}}if(ok){setCopied(true);setTimeout(()=>setCopied(false),1600)}};
 useEffect(()=>{const observer=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));return()=>observer.disconnect()},[]);
 useEffect(()=>{const rails=[heroRail.current,experienceRail.current].filter(Boolean);const timers=rails.map(rail=>setInterval(()=>{if(window.innerWidth>700||document.hidden)return;const max=rail.scrollWidth-rail.clientWidth;if(max<=0)return;rail.scrollTo({left:rail.scrollLeft+rail.clientWidth*.72,behavior:'smooth'});if(rail.scrollLeft>=max-8)setTimeout(()=>rail.scrollTo({left:0,behavior:'smooth'}),650)},3200));return()=>timers.forEach(clearInterval)},[]);
 return <div className="site" id="top">
  <header className="header"><a className="brand" href="#top"><img className="brand-mark" src="/triglav-logo.jpg" alt="Triglav logo"/><span>TRIGLAV<br/><b>CARD</b></span></a><nav><a href="#experience">Experience</a><a href="#token">Token</a><a href="#get">Get Triglav Card Now</a></nav><div className="header-actions"><a className="x-button" href={X_URL} target="_blank" rel="noreferrer" aria-label="Triglav on X"><span>𝕏</span> X</a><a className="header-cta" href={PLAY_STORE_URL} target="_blank" rel="noreferrer">Get Triglav Card Now <ArrowUpRight size={14}/></a></div><button className="menu" onClick={()=>setMenu(!menu)} aria-label="Menu">{menu?<X/>:<Menu/>}</button></header>
  {menu&&<div className="mobile-menu"><a href="#experience" onClick={()=>setMenu(false)}>Experience</a><a href="#token" onClick={()=>setMenu(false)}>Token</a><a href={X_URL} target="_blank" rel="noreferrer">𝕏 X / Twitter</a><a href="#get" onClick={()=>setMenu(false)}>Get Triglav Card Now</a></div>}
  <main>
   <section className="hero reveal"><div className="token-panel" id="token"><div><span className="token-label">TRIGLAV TOKEN</span><div className="fx-lightleak" data-text="$TRIGLAV">$TRIGLAV</div><code>{TOKEN_ADDRESS}</code></div><div className="token-actions"><button onClick={copyCA}>{copied?<Check size={15}/>:<Copy size={15}/>} {copied?'Copied':'Copy CA'}</button><a className="buy-button" href={BUY_URL} target="_blank" rel="noreferrer">BUY <ArrowUpRight size={15}/></a></div></div><div className="hero-brand"><img className="brand-mark large" src="/triglav-logo.jpg" alt="Triglav logo"/><span>TRIGLAV<br/><b>CARD</b></span></div><h1 className="hero-type"><span className="fx-typewriter fx-typewriter-main">Benefits at hand.</span><span className="fx-typewriter fx-typewriter-accent">Offers made for you.</span></h1><p>Triglav Card is the digital version of our well-known loyalty program, bringing exclusive discounts, partner benefits, and personalized offers to your mobile.</p><a className="store-button" href={PLAY_STORE_URL} target="_blank" rel="noreferrer"><span className="play-icon" aria-hidden="true"><svg viewBox="0 0 32 32"><path className="play-blue" d="M4 3.4c-.6.6-1 1.5-1 2.7v19.8c0 1.2.4 2.1 1 2.7l.2.2L19.5 16v-.3L4.2 3.2z"/><path className="play-green" d="M24.6 21.1 19.5 16v-.3l5.1-5.1.1.1 6.1 3.5c1.7 1 1.7 2.5 0 3.5l-6.1 3.4z"/><path className="play-yellow" d="m24.7 21-5.2-5.2L4 28.8c.7.7 1.8.8 3 .1l17.7-7.9z"/><path className="play-red" d="M24.7 10.7 7 3c-1.2-.7-2.3-.6-3 .1l15.5 15.2z"/></svg></span><span><small>GET IT ON</small><strong>Google Play</strong></span></a><div className="hero-devices" ref={heroRail}>{HERO_ASSETS.map((src,i)=><img key={src} src={'/'+src} alt={`Triglav Card mobile app screen ${i+1}`}/>)}</div></section>
   <section className="experience reveal" id="experience"><p className="eyebrow">EXPERIENCE</p><h2>benefits at your fingertips</h2><p className="experience-copy">Discover exclusive discounts and personalized offers from a wide range of Triglav partner companies — always with you, wherever you go.</p><div className="three-devices" ref={experienceRail}>{EXPERIENCE_ASSETS.map((src,i)=><img key={src} src={'/'+src} alt={`Triglav Card app experience screen ${i+6}`}/>)}</div></section>
   <section className="cta reveal" id="get"><p className="eyebrow">TRIGLAV CARD</p><h2 className="cta-scanner"><span className="fx-scanner">Get Triglav</span><span className="fx-scanner fx-scanner-accent">Card Now.</span></h2><p className="contact-copy">Learn more about the loyalty program at <a href="mailto:info@triglavzivot.mk">info@triglavzivot.mk</a> · <a href="tel:0800044444">0800 04444</a> · Viber <a href="viber://chat?number=%2B38978200580">078/200-580</a></p><a className="store-button dark" href={PLAY_STORE_URL} target="_blank" rel="noreferrer"><span className="play-icon" aria-hidden="true"><svg viewBox="0 0 32 32"><path className="play-blue" d="M4 3.4c-.6.6-1 1.5-1 2.7v19.8c0 1.2.4 2.1 1 2.7l.2.2L19.5 16v-.3L4.2 3.2z"/><path className="play-green" d="M24.6 21.1 19.5 16v-.3l5.1-5.1.1.1 6.1 3.5c1.7 1 1.7 2.5 0 3.5l-6.1 3.4z"/><path className="play-yellow" d="m24.7 21-5.2-5.2L4 28.8c.7.7 1.8.8 3 .1l17.7-7.9z"/><path className="play-red" d="M24.7 10.7 7 3c-1.2-.7-2.3-.6-3 .1l15.5 15.2z"/></svg></span><span><small>GET IT ON</small><strong>Google Play</strong></span></a></section>
  </main>
  <footer><a className="brand" href="#top"><img className="brand-mark" src="/triglav-logo.jpg" alt="Triglav logo"/><span>TRIGLAV<br/><b>CARD</b></span></a><span>© 2026 TRIGLAV CARD</span></footer>
 </div>
}
createRoot(document.getElementById('root')).render(<App/>);
